VoteOnIt_WebApp/Controllers/SurveysController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using VoteOnIt_WebApp.Models;

namespace VoteOnIt_WebApp.Controllers
{
    public class SurveysController : Controller
    {

        // GET: Surveys
        public async Task<ActionResult> Index()
        {
            List<SurveyViewModel> list = new List<SurveyViewModel>();
            IEnumerable<Survey> tempList = null;
            var currentUser = User.Identity.Name;
            // Get a list of all surveys
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://voteonitws.azurewebsites.net/");
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage response = await client.GetAsync("api/survey");
                if (response.IsSuccessStatusCode)
                {
                    tempList = await response.Content.ReadAsAsync<IEnumerable<Survey>>();
                    foreach (var survey in tempList.Where(x=>!x.IsPrivate || x.CreatedById == currentUser))
                    {
                        list.Add(new SurveyViewModel()
                        {
                            Id = survey.Id,
                            CreatedById = survey.CreatedById,
                            Title = survey.Title,
                            Description = survey.Description,
                            DateCreated = survey.DateCreated,
                            ValidFrom = survey.ValidFrom,
                            ValidTo = survey.ValidTo,
                            IsPrivate = survey.IsPrivate,
                            Tags = new List<string>(),
                            Comments = new List<Comment>(),
                            Options = new List<Option>(),
                            Responses = new List<Response>(),
                            Questions = survey.Questions,
                        });
                    }
                }
            }
                return View(list);
        }


        // GET: Surveys by user
        public async Task<ActionResult> MySurveys()
        {
            List<SurveyViewModel> list = new List<SurveyViewModel>();
            IEnumerable<Survey> tempList = null;
            // Get a list of all surveys
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://voteonitws.azurewebsites.net/");
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                var currentUser = User.Identity.Name;
                // get surveys from user email
                HttpResponseMessage response = await client.GetAsync(string.Format("api/survey/get/{0}/", currentUser));
                var content = response.Content.Headers.ContentLength.Value;
                if (response.IsSuccessStatusCode && content > 2)
                {
                    tempList = await response.Content.ReadAsAsync<IEnumerable<Survey>>();

                    foreach (var survey in tempList)
                    {
                        list.Add(new SurveyViewModel()
                        {
                            Id = survey.Id,
                            CreatedById = survey.CreatedById,
                            Title = survey.Title,
                            Description = survey.Description,
                            DateCreated = survey.DateCreated,
                            ValidFrom = survey.ValidFrom,
                            ValidTo = survey.ValidTo,
                            IsPrivate = survey.IsPrivate,
                            Tags = new List<string>(),
                            Comments = new List<Comment>(),
                            Questions = survey.Questions,
                            Responses = new List<Response>(),
                        });
                    }
                }
                else
                {
                    list = null;
                }
            }
            return View(list);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(CreateSurveyViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://voteonitws.azurewebsites.net/");
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                // HTTP POST AddSurvey
                // Not all arguments are mandatory. Values can be null.
                Survey newSurvey = new Survey()
                {
                    Title = model.Title,
                    CreatedById = User.Identity.Name,
                    Description = model.Description,
                    DateCreated = DateTime.Now,
                    ValidFrom = model.ValidFrom,
                    ValidTo = model.ValidTo,
                    IsPrivate = model.IsPrivate,
                    Questions = model.Questions
                };
                HttpResponseMessage response = await client.PostAsJsonAsync("api/survey", newSurvey);

                if (response.IsSuccessStatusCode)
                {
                    return Redirect("~/Surveys/MySurveys"); // redirect to my surves list
                }
                return View(model);
            }
        }


        [HttpGet]
        public ActionResult Delete()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Delete(DeleteSurveyViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://voteonitws.azurewebsites.net/");
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                // Get cookie values
                     string userEmail = User.Identity.Name;

                // Get Survey ID
                string url = System.Web.HttpContext.Current.Request.Url.AbsolutePath;
                string lastPart = url.Split('/').Last();
                string surveyID = lastPart;

                // Get user from email
                User currentUser = null;
                HttpResponseMessage response1 = await client.GetAsync(string.Format("api/user/email/{0}/", userEmail));
                currentUser = await response1.Content.ReadAsAsync<User>();

                // Get Survey from id
                Survey currentSurvey = null;
                HttpResponseMessage response2 = await client.GetAsync(string.Format("api/survey/{0}/", surveyID));
                currentSurvey = await response2.Content.ReadAsAsync<Survey>();

                if (currentSurvey.CreatedById == currentUser.Email)
                {
                   
                    // HTTP GET CheckLogin
                    // Check if current password match the email
                    HttpResponseMessage response3 = await client.GetAsync(string.Format("api/account/{0}/{1}", userEmail, model.CurrentPassword));
                    User loggedUser = await response3.Content.ReadAsAsync<User>();
                    if (response3.IsSuccessStatusCode && loggedUser != null)
                    {
                        // HTTP Delete survey
                        // check if survey was deleted correctly
                        HttpResponseMessage response4 = await client.DeleteAsync(string.Format("api/survey/{0}", surveyID));
                        Boolean statusCode = await response4.Content.ReadAsAsync<Boolean>();
                        if (response4.IsSuccessStatusCode && statusCode == true)
                        {

                            return Redirect("~/Surveys/MySurveys");
                        }
                        else
                        {

                            ModelState.AddModelError("CurrentPassword", "Something went wrong, please try again later");
                            return View(model);
                        }
                    }
                    else
                    {

                        ModelState.AddModelError("CurrentPassword", "Current password did not match");
                        return View(model);
                    }
                }
                else
                {
                    ModelState.AddModelError("CurrentPassword", "You are not owner of this survey");
                    return View(model);
                }
            }
        }

        [HttpGet]
        public async Task<ActionResult> Edit()
        {
            Survey currentSurvey = null;
            EditSurveyViewModel model = null;
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://voteonitws.azurewebsites.net/");
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));


VoteOnIt_WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Vote on it</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Vote On It", "Index", "Surveys", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @if (!HttpContext.Current.User.Identity.IsAuthenticated)
                {
                    <ul class="nav navbar-nav">
                    </ul>
                        <ul class="nav navbar-nav navbar-right">
                            <li>@Html.ActionLink("Login", "Index", "Accounts", new { area = "" }, null)</li>
                            <li>@Html.ActionLink("Register", "Register", "Accounts", new { area = "" }, null)</li>
                        </ul>

                }
                else
                {
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Groups", "Index", "Groups", new { area = "" }, null)</li>
                        <li>@Html.ActionLink("Survey", "Index", "Surveys", new { area = "" }, null)</li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <div class="dropdown" style="position:relative;top: 15px;">
                                <button class="btn btn-warning btn-xs dropdown-toggle" type="button" id="menu1" data-toggle="dropdown">
                                    <span class="glyphicon glyphicon-list"></span>
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
                                    <li role="presentation"><a role="menuitem" tabindex="-1" href="/Surveys/Create"><span class="glyphicon glyphicon-question-sign" style="position:relative;right: 10px;"></span>Create Survey</a></li>
                                    <li role="presentation"><a role="menuitem" tabindex="-1" href="/Surveys/MySurveys"><span class="glyphicon glyphicon-list" style="position:relative;right: 10px;"></span>My Surveys</a></li>
                                    <li role="presentation" class="divider"></li>
                                    <li role="presentation"><a role="menuitem" tabindex="-1" href="/Accounts/Settings"><span class="glyphicon glyphicon-cog" style="position:relative;right: 10px;"></span>Settings</a></li>
                                    <li role="presentation" class="divider"></li>
                                    <li role="presentation"><a role="menuitem" tabindex="-1" href="/Accounts/Logout"><span class="glyphicon glyphicon-off" style="position:relative;right: 10px;"></span>Logout</a></li>
                                </ul>
                            </div>
                        <!--<li>@Html.ActionLink("Logout", "Logout", "Accounts")</li>-->
                    </ul>
                }
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>CodeBlockers Inc&copy; @DateTime.Now.Year </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>