VoteOnIt_WebApp/Models/AccountViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace VoteOnIt_WebApp.Models
{

    public class LoginViewModel
    {
        [Required]
        [DataType(DataType.EmailAddress)]
        public String Email { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public String Password { get; set; }
    }

    public class RegisterViewModel
    {
        [Required]
        public String Username { get; set; }
        [Required]
        public String Firstname { get; set; }
        [Required]
        public String Lastname { get; set; }
        [Required]
        public String Gender { get; set; }
        [Required]
        [DataType(DataType.EmailAddress)]
        public String Email { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public String Password { get; set; }
        [DataType(DataType.Date)]
        public DateTime DateOfBirth { get; set; }
    }

    public class EditDetailsViewModel
    {
        [Display(Name = "Username")]
        public string Username { get; set; }

        [Display(Name = "FirstName")]
        public string FirstName { get; set; }

        [Display(Name = "LastName")]
        public string LastName { get; set; }

        [Display(Name = "Gender")]
        public string Gender { get; set; }

        [DataType(DataType.EmailAddress)]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "DateOfBirth")]
        public DateTime DateOfBirth { get; set; }
    }

    public class EditPasswordViewModel
    {
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Current password")]
        public string currentPassword { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The new password must be at least 6 characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string newPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("newPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string confirmPassword { get; set; }
    }

    public class DeleteAccountViewModel
    {
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Current password")]
        public string CurrentPassword { get; set; }
    }
}

VoteOnIt_WebApp/Controllers/AccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using VoteOnIt_WebApp.Models;
using System.Threading.Tasks;

namespace VoteOnIt_WebApp.Controllers
{
    public class AccountsController : Controller
    {
        //private UserController _userController = new UserController();

		[HttpGet]
        // GET: Account
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Index(LoginViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://voteonitws.azurewebsites.net/");
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                // HTTP GET CheckLogin
                HttpResponseMessage response = await client.GetAsync(string.Format("api/account/{0}/{1}", model.Email, model.Password));
                User loggedUser = await response.Content.ReadAsAsync<User>();
                if (response.IsSuccessStatusCode && loggedUser != null)
                {
                    // set up authentication
                    FormsAuthentication.SetAuthCookie(model.Email, false);

                    // TODO: set up role and identification for current user

                    //redirect to members, just home for now
                    return Redirect("~/Surveys");
                }
            }

            ModelState.AddModelError("Email", "The credentials does not match");
            return View(model);
        }

        public ActionResult Logout()
          {
              FormsAuthentication.SignOut();
              return Redirect("Index");
          }

		  [HttpGet]
          [AllowAnonymous]
          public ActionResult Register()
          {
			return View();
          }

        [HttpPost]
        public async Task<ActionResult> Register(RegisterViewModel model)
        {

            if (!ModelState.IsValid)
            {
                return View(model);
            }
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://voteonitws.azurewebsites.net/");
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                // HTTP POST AddUser
                // Not all arguments are mandatory. Values can be null.

                User newUser = new User();
                newUser.Username = model.Username;
                newUser.FirstName = model.Firstname;
                newUser.LastName = model.Lastname;
                newUser.Email = model.Email;
                newUser.Gender = model.Gender;
                newUser.Password = model.Password;
                newUser.DateOfBirth = model.DateOfBirth;

                HttpResponseMessage response = await client.PostAsJsonAsync("api/user", newUser);

                if (response.IsSuccessStatusCode)
                {
                    return Redirect("Index"); // redirect to login page
                }
                else
                {
                    ModelState.AddModelError("Email", "Username or Email already in use");
                    return View(model);
                }
            }
        }

        [HttpGet]
        public ActionResult Settings()
        {
            return View();
        }

        [HttpGet]
        public async Task<ActionResult> EditDetails()
        {
            User currentUser = null;
            EditDetailsViewModel model = null;
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://voteonitws.azurewebsites.net/");
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                // Get cookie values
                string userEmail = User.Identity.Name;

                HttpResponseMessage response = await client.GetAsync(string.Format("api/user/email/{0}/", userEmail));
                currentUser = await response.Content.ReadAsAsync<User>();

            }

            model = new EditDetailsViewModel()
            {
                Username = currentUser.Username,
                Email = currentUser.Email,
                DateOfBirth = currentUser.DateOfBirth,
                FirstName = currentUser.FirstName,
                LastName = currentUser.LastName,
                Gender = currentUser.Gender
            };
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> EditDetails(EditDetailsViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://voteonitws.azurewebsites.net/");
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                // Get cookie values
                string userEmail = User.Identity.Name;

                User currentUser = null;
                User updatedUser = new User();

                // Get current user data from the db
                HttpResponseMessage response1 = await client.GetAsync(string.Format("api/user/email/{0}/", userEmail));
                currentUser = await response1.Content.ReadAsAsync<User>();
                // Check for any changes, then set new values
                if (model.Username != currentUser.Username)
                {
                    // GET userExist
                    HttpResponseMessage userresponse = await client.GetAsync(string.Format("api/user/exists/{0}/", model.Username));
                    Boolean userExist = await userresponse.Content.ReadAsAsync<Boolean>();
                    if (userresponse.IsSuccessStatusCode && userExist == false)
                    {
                        updatedUser.Username = model.Username;
                    }
                    else
                    {
                        ModelState.AddModelError("Username", "Username is allready in use");
                        return View(model);
                    }
                }
                if (model.FirstName != currentUser.FirstName)
                {
                    updatedUser.FirstName = model.FirstName;
                }
                if (model.LastName != currentUser.LastName)
                {
                    updatedUser.LastName = model.LastName;
                }
                if (model.Gender != currentUser.Gender)
                {
                    updatedUser.Gender = model.Gender;
                }
                if (model.Email != currentUser.Email)
                {
                    // GET emailExist
                    HttpResponseMessage emailresponse = await client.GetAsync(string.Format("api/user/email/exists/{0}/", model.Email));
                    Boolean emailExist = await emailresponse.Content.ReadAsAsync<Boolean>();
                    if (emailresponse.IsSuccessStatusCode && emailExist == false)
                    {
                        updatedUser.Email = model.Email;

                        // update authentication
                        FormsAuthentication.SetAuthCookie(model.Email, false);
                    }
                    else
                    {
                        ModelState.AddModelError("Email", "Email is allready in use");
                        return View(model);
                    }
                }
                if (model.DateOfBirth != currentUser.DateOfBirth)
                {
                    updatedUser.DateOfBirth = model.DateOfBirth;
                }

                // Check for any changes, then updates user
                if (model.Username != currentUser.Username || model.FirstName != currentUser.FirstName || model.LastName != currentUser.LastName || model.Gender != currentUser.Gender || model.Email != currentUser.Email || model.DateOfBirth != currentUser.DateOfBirth)
                {
                    updatedUser.Id = currentUser.Id;
                    // HTTP Put Updateuser
                    // Updates the data for updated user
                    HttpResponseMessage response2 = await client.PutAsJsonAsync("api/user", updatedUser);
                    if (response2.IsSuccessStatusCode)
                    {
                        return Redirect("Settings");
                    }
                    else
                    {
                        ModelState.AddModelError("Username", "Something went wrong, please try again later");
                        return View(model);
                    }
                }

                return View(model);
            }
        }

        [HttpGet]
        public ActionResult EditPassword()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> EditPassword(EditPasswordViewModel model)
        {

            if (!ModelState.IsValid)
            {
                return View(model);
            }
            using (var client = new HttpClient())
            {

VoteOnIt_WebApp/Views/Accounts/DeleteAccount.cshtml
@model VoteOnIt_WebApp.Models.DeleteAccountViewModel

@{
    ViewBag.Title = "Delete Account";
}

<div class="alert alert-waring">
    <h3>Delete Account</h3>
</div>

@using (Html.BeginForm())
{
@Html.AntiForgeryToken()
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CurrentPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CurrentPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CurrentPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Delete Account" class="btn btn-danger" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Settings", "Settings")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

VoteOnIt_WebApp/Views/Accounts/EditAddress.cshtml

@{
    ViewBag.Title = "Change Address";
}

<div class="alert alert-waring">
    <h3>Edit User Adress</h3>
</div>

@using (Html.BeginForm())
{
@Html.AntiForgeryToken()
    <hr />
    <div class="form-horizontal">
        <div class="panel panel-primary">
            <div class="panel-heading"><span class="glyphicon glyphicon-user" style="position:relative;right: 5px;"></span>Account Settings</div>
                <div class="panel-body">@Html.ActionLink("Change Account Details", "EditDetails", "Account", new { area = "" }, null)</div>
                <div class="panel-body">@Html.ActionLink("Change Account Address", "EditAddress", "Account", new { area = "" }, null)</div>
                <div class="panel-body">@Html.ActionLink("Change Password", "EditPassword", "Account", new { area = "" }, null)</div>   
         </div>
        <div class="panel panel-primary">
            <div class="panel-heading"><span class="glyphicon glyphicon-cog" style="position:relative;right: 5px;"></span>General Settings</div>
            <div class="panel-body">@Html.ActionLink("Delete Account", "DeleteAccount", "Account", new { area = "" }, null)</div>
        </div>
    </div>
}

VoteOnIt_WebApp/Views/Accounts/EditDetails.cshtml
@model VoteOnIt_WebApp.Models.EditDetailsViewModel

@{
    ViewBag.Title = "EditDetails";
}

<div class="alert alert-waring">
    <h3>Edit User Details</h3>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to settings", "Settings")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

VoteOnIt_WebApp/Views/Accounts/EditPassword.cshtml
@model VoteOnIt_WebApp.Models.EditPasswordViewModel

@{
    ViewBag.Title = "Change Password";
}

<div class="alert alert-waring">
    <h3>Edit Password</h3>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.currentPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.currentPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.currentPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.newPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.newPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.newPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.confirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.confirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.confirmPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Settings", "Settings")
</div>

VoteOnIt_WebApp/Views/Accounts/Index.cshtml
@model VoteOnIt_WebApp.Models.LoginViewModel

@{
    ViewBag.Title = "Index";
}

<div class="alert alert-info">
    <h3>Login</h3>
</div>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

VoteOnIt_WebApp/Views/Accounts/Register.cshtml
@model VoteOnIt_WebApp.Models.RegisterViewModel

@{
    ViewBag.Title = "Register";
}

<div class="alert alert-success">
    <h3>Create User</h3>
</div>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>RegisterViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Firstname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Firstname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Firstname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lastname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Lastname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Lastname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" , autocomplete = "off" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

VoteOnIt_WebApp/Views/Accounts/Settings.cshtml

@{
    ViewBag.Title = "Settings";
}

<div class="alert alert-info">
    <h3>User Settings</h3>
</div>

@using (Html.BeginForm())
{
@Html.AntiForgeryToken()
    <hr />
    <div class="form-horizontal">
        <div class="panel panel-primary">
            <div class="panel-heading"><span class="glyphicon glyphicon-user" style="position:relative;right: 5px;"></span>Account Settings</div>
                <div class="panel-body">@Html.ActionLink("Edit Account Details", "EditDetails", "Accounts", new { area = "" }, null)</div>
                <div class="panel-body">@Html.ActionLink("Change Password", "EditPassword", "Accounts", new { area = "" }, null)</div>   
         </div>
        <div class="panel panel-primary">
            <div class="panel-heading"><span class="glyphicon glyphicon-cog" style="position:relative;right: 5px;"></span>General Settings</div>
            <div class="panel-body">@Html.ActionLink("Delete Account", "DeleteAccount", "Accounts", new { area = "" }, null)</div>
        </div>
    </div>
}